server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location ~ ^/documentation(?<doc_path>/.*)$ {
        # Statically serve the files asked after the documentation path
        try_files $doc_path $doc_path.html $doc_path/index.html $doc_path/ =404;
    }

    location = /documentation {
        return 301 $scheme://$http_host/documentation/;
    }

    location = / {
        return 301 $scheme://$http_host/documentation/;
    }

}