import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    introSidebar: [
        'intro/welcome',
        'intro/solutions',
        'intro/get-started',
        'intro/graphical-overview',
        {
            type: 'category',
            label: 'Architecture',
            items: [{
                type: 'autogenerated',
                dirName: 'intro/architecture',
            }],
        }
    ],
    clientUsageSidebar: [
                {
            type: 'category',
            label: 'Client usage',
            items: [{
                type: 'autogenerated',
                dirName: 'client-usage',
            }],
        },
    ],
    platformUsageSidebar: [
        {
            type: 'category',
            label: 'Platform Usage',
            items: [{
                type: 'autogenerated',
                dirName: 'platform-usage',
            }],
        },
    ],
    toolDeveloperSidebar: [
        {
            type: 'autogenerated',
            dirName: 'tool-dev',
        }
    ],
    deploymentSidebar: [
        'deployment/deployment-overview',
        {
            type: 'category',
            label: 'Clinic Node',
            items: [
                'deployment/deploy-client',
                'deployment/backup-client',
                'deployment/deploy-local-dind',
            ],
        },
        {
            type: 'category',
            label: 'Global Server',
            items: ['deployment/deploy-global', 'deployment/self-deployment-guide'],
        },
    ],
    tutorialsSidebar: [
        'tutorials/tutorial-overview',
        {
            type: 'category',
            label: 'Hackathon: Hospital Readmission',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'tutorials/us-130',
                },
            ],
        },
        {
            type: 'category',
            label: 'Walkthroughs',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'tutorials/walkthroughs',
                },
            ],
        },
    ],
    coreDeveloperSidebar: [
        {
            type: 'autogenerated',
            dirName: 'contribution-guide',
        },
    ],
};

export default sidebars;
